<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\ConnectToPhone.Core\ConnectToPhone.Core.csproj" />
    <ProjectReference Include="..\..\src\ConnectToPhone.Transports\ConnectToPhone.Transports.csproj" />
    <ProjectReference Include="..\..\src\ConnectToPhone.Explorer\ConnectToPhone.Explorer.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
